ureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: hystrix
feign:
  hystrix:
    enabled: true
management:
   security:
     enabled: false